### ISSUE TITLE
Error Base table or view not found: 1146 Table 'drupal.undefinedkey_value' 

### ISSUE THREAD

**Issue by dstorozhuk** [ProboCI/probo#125] opened 2017-11-13 16:53 UTC
I see the new release v3.11.0 added 2 hours ago, and after that my probo.ci project get failed with  the following errors on Drupal provision step (`Mysite site provision`) with the following errors:

```
[error]  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'drupal.undefinedkey_value' doesn't exist: DELETE FROM {key_value} 
63WHERE (name IN (:db_condition_placeholder_0)) AND (collection = :db_condition_placeholder_1); Array
(
    [:db_condition_placeholder_0] => drupal_css_cache_files
    [:db_condition_placeholder_1] => state
)
 ```

here is my .probo.ci file
```
basicAuth:
  username: user
  password: pass
assets:
  - db.sql.gz
steps:
  - name: Upgrade to php 7
    plugin: Script
    script: |
      echo 'exit 0' > /usr/sbin/policy-rc.d
      apt-get update
      apt-get install -y software-properties-common language-pack-en-base
      LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/php
      apt-get update
      DEBIAN_FRONTEND=noninteractive apt-get install -y php7.1 libapache2-mod-php7.1 php7.1-gd php7.1-curl php7.1-json php7.1-mbstring php7.1-mysql php7.1-mcrypt php7.1-imagick php7.1-dev php7.1-gmp php7.1-xml
      cp /etc/php5/mods-available/general_settings.ini /etc/php/7.1/apache2/conf.d/20-general_settings.ini
      a2dismod php5
      a2enmod php7.1
      a2enmod mpm_prefork
      apache2ctl graceful
  - name: opcache
    plugin: Script
    script: |
      echo 'opcache.enable=1' >> /etc/php/7.1/mods-available/opcache.ini
      echo 'opcache.enable_cli=1' >> /etc/php/7.1/mods-available/opcache.ini
      echo 'opcache.memory_consumption=192' >> /etc/php/7.1/mods-available/opcache.ini
      echo 'opcache.interned_strings_buffer=16' >> /etc/php/7.1/mods-available/opcache.ini
      echo 'opcache.max_accelerated_files=3907' >> /etc/php/7.1/mods-available/opcache.ini
      echo 'opcache.validate_timestamps=0' >> /etc/php/7.1/mods-available/opcache.ini
      echo 'opcache.fast_shutdown=1' >> /etc/php/7.1/mods-available/opcache.ini
      apache2ctl graceful
  - name: Mysite site provision
    drupalVersion: 8
    plugin: Drupal
    databaseGzipped: true
    databaseUpdates: true
    clearCaches: false
    database:db.sql.gz
    databaseName: drupal
    databaseUser: drupal
    subDirectory: docroot
    settingsAppend: |
      $config_directories = ['sync' => 'sites/default/config/sync'];
  - name: Post deploy commands
    plugin: Script
    script: |
      drush cim -y
      drush en -y stage_file_proxy
      drush -y config-set stage_file_proxy.settings origin 'http://url.com/'
      bin/drush -y config-set system.image toolkit 'gd'
      drush -y config-set system.file path.temporary '/tmp'
      drush cr
  - name: Uninstall Node
    plugin: Shell
    command: 'apt-get remove -y nodejs'
  - name: Add nodesource debs
    plugin: Shell
    command: 'wget -qO- https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add - ; echo "deb https://deb.nodesource.com/node_4.x trusty main" > /etc/apt/sources.list.d/nodesource.list ; echo "deb-src https://deb.nodesource.com/node_4.x trusty main" >> /etc/apt/sources.list.d/nodesource.list'
  - name: Install nodejs
    plugin: Shell
    command: 'apt-get update ; apt-get install --fix-missing -y nodejs'
  - name: Install gulp-cli
    plugin: Shell
    command: 'npm install -g gulp; npm install -g gulp-cli'
  - name: Install bower
    plugin: Shell
    command: 'npm install -g bower'
  - name: Pull down node modules
    plugin: Shell
    command: 'cd $SRC_DIR/docroot/themes/mytheme; npm install;'
  - name: Install bower dependecies
    plugin: Shell
    command: 'cd $SRC_DIR/docroot/themes/mytheme; bower --verbose --allow-root install;'
  - name: Compile frontend assets
    plugin: Shell
    command: 'cd $SRC_DIR/docroot/themes/mytheme; gulp build;'
```

**Comment by sk33lz** [comment] 2017-12-01 21:11
Dima,

This was caused by a bug in a new setting we added for databasePrefix. The fix for this has been deployed, so let me know if it's still an issue for you on Live.

Thanks,

Jason

**Comment by dstorozhuk** [comment] 2017-12-02 05:51
It works now, thanks

**Comment by sk33lz** [comment] 2017-12-04 17:05
Great. I'll close this out.

**Closed by sk33lz** 2017-12-04 17:05 UTC
